### ISSUE TITLE
Hello, how to add procfs for key disabler?

### ISSUE THREAD

**Issue by GuaiYiHu** [xiaomi-dev-playground/android_kernel_xiaomi_libra#1]
I have made some changes by refering to your commits, but it doesn't work...
Here is my commit :
https://github.com/GuaiYiHu/android_kernel_xiaomi_leo/commit/ca90128fc9c908a84031e6d3261dadf8f9191e56

**Comment by Hikari-no-Tenshi** [comment]
Hello.
You need commits:
https://github.com/xiaomi-dev-playground/android_kernel_xiaomi_libra/commit/3ae62fcd603da6b7f192259b056b214ef88d3697
https://github.com/xiaomi-dev-playground/android_kernel_xiaomi_libra/commit/c2bff3085af126ff080d31a5930b21c61c1992f1
https://github.com/xiaomi-dev-playground/android_kernel_xiaomi_libra/commit/2a92bbb39174eec164981b36f99160c109fa7380
And this: https://github.com/xiaomi-dev-playground/android_device_xiaomi_libra/blob/cm-14.1-q/cmhw/org/cyanogenmod/hardware/KeyDisabler.java

**Comment by GuaiYiHu** [comment]
Thanks~
